[package]
name = "ch02"
version = "0.1.0"
authors = ["Pavel Karateev <lancelote.du.lac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
regex = "1.4.5"
clap = "3.0.0-beta.2"
