name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    container: rustlang/rust:nightly
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup toolchain install nightly --allow-downgrade -c clippy rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
    - name: Format
      run: cargo fmt --all -- --check
    - name: Run check
      run: cargo check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
